.nh
.TH KUBERNETES(1) kubernetes User Manuals
Eric Paris
Jan 2015

.SH NAME
.PP
kubectl drain \- Drain node in preparation for maintenance


.SH SYNOPSIS
.PP
\fBkubectl drain\fP [OPTIONS]


.SH DESCRIPTION
.PP
Drain node in preparation for maintenance.

.PP
The given node will be marked unschedulable to prevent new pods from arriving. 'drain' evicts the pods if the API server supports https://kubernetes.io/docs/concepts/workloads/pods/disruptions/ . Otherwise, it will use normal DELETE to delete the pods. The 'drain' evicts or deletes all pods except mirror pods (which cannot be deleted through the API server).  If there are daemon set\-managed pods, drain will not proceed without \-\-ignore\-daemonsets, and regardless it will not delete any daemon set\-managed pods, because those pods would be immediately replaced by the daemon set controller, which ignores unschedulable markings.  If there are any pods that are neither mirror pods nor managed by a replication controller, replica set, daemon set, stateful set, or job, then drain will not delete any pods unless you use \-\-force.  \-\-force will also allow deletion to proceed if the managing resource of one or more pods is missing.

.PP
\&'drain' waits for graceful termination. You should not operate on the machine until the command completes.

.PP
When you are ready to put the node back into service, use kubectl uncordon, which will make the node schedulable again.

.PP
https://kubernetes.io/images/docs/kubectl\_drain.svg


.SH OPTIONS
.PP
\fB\-\-chunk\-size\fP=500
	Return large lists in chunks rather than all at once. Pass 0 to disable. This flag is beta and may change in the future.

.PP
\fB\-\-delete\-emptydir\-data\fP=false
	Continue even if there are pods using emptyDir (local data that will be deleted when the node is drained).

.PP
\fB\-\-delete\-local\-data\fP=false
	Continue even if there are pods using emptyDir (local data that will be deleted when the node is drained).

.PP
\fB\-\-disable\-eviction\fP=false
	Force drain to use delete, even if eviction is supported. This will bypass checking PodDisruptionBudgets, use with caution.

.PP
\fB\-\-dry\-run\fP="none"
	Must be "none", "server", or "client". If client strategy, only print the object that would be sent, without sending it. If server strategy, submit server\-side request without persisting the resource.

.PP
\fB\-\-force\fP=false
	Continue even if there are pods not managed by a ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet.

.PP
\fB\-\-grace\-period\fP=\-1
	Period of time in seconds given to each pod to terminate gracefully. If negative, the default value specified in the pod will be used.

.PP
\fB\-\-ignore\-daemonsets\fP=false
	Ignore DaemonSet\-managed pods.

.PP
\fB\-\-pod\-selector\fP=""
	Label selector to filter pods on the node

.PP
\fB\-l\fP, \fB\-\-selector\fP=""
	Selector (label query) to filter on

.PP
\fB\-\-skip\-wait\-for\-delete\-timeout\fP=0
	If pod DeletionTimestamp older than N seconds, skip waiting for the pod.  Seconds must be greater than 0 to skip.

.PP
\fB\-\-timeout\fP=0s
	The length of time to wait before giving up, zero means infinite


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-as\fP=""
	Username to impersonate for the operation. User could be a regular user or a service account in a namespace.

.PP
\fB\-\-as\-group\fP=[]
	Group to impersonate for the operation, this flag can be repeated to specify multiple groups.

.PP
\fB\-\-as\-uid\fP=""
	UID to impersonate for the operation.

.PP
\fB\-\-azure\-container\-registry\-config\fP=""
	Path to the file containing Azure container registry configuration information.

.PP
\fB\-\-cache\-dir\fP="/tmp/kubernetes\-cli\-20211216\-7728\-4tsrr/.brew\_home/.kube/cache"
	Default cache directory

.PP
\fB\-\-certificate\-authority\fP=""
	Path to a cert file for the certificate authority

.PP
\fB\-\-client\-certificate\fP=""
	Path to a client certificate file for TLS

.PP
\fB\-\-client\-key\fP=""
	Path to a client key file for TLS

.PP
\fB\-\-cluster\fP=""
	The name of the kubeconfig cluster to use

.PP
\fB\-\-context\fP=""
	The name of the kubeconfig context to use

.PP
\fB\-\-insecure\-skip\-tls\-verify\fP=false
	If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure

.PP
\fB\-\-kubeconfig\fP=""
	Path to the kubeconfig file to use for CLI requests.

.PP
\fB\-\-match\-server\-version\fP=false
	Require server version to match client version

.PP
\fB\-n\fP, \fB\-\-namespace\fP=""
	If present, the namespace scope for this CLI request

.PP
\fB\-\-password\fP=""
	Password for basic authentication to the API server

.PP
\fB\-\-profile\fP="none"
	Name of profile to capture. One of (none|cpu|heap|goroutine|threadcreate|block|mutex)

.PP
\fB\-\-profile\-output\fP="profile.pprof"
	Name of the file to write the profile to

.PP
\fB\-\-request\-timeout\fP="0"
	The length of time to wait before giving up on a single server request. Non\-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests.

.PP
\fB\-s\fP, \fB\-\-server\fP=""
	The address and port of the Kubernetes API server

.PP
\fB\-\-tls\-server\-name\fP=""
	Server name to use for server certificate validation. If it is not provided, the hostname used to contact the server is used

.PP
\fB\-\-token\fP=""
	Bearer token for authentication to the API server

.PP
\fB\-\-user\fP=""
	The name of the kubeconfig user to use

.PP
\fB\-\-username\fP=""
	Username for basic authentication to the API server

.PP
\fB\-\-version\fP=false
	Print version information and quit

.PP
\fB\-\-warnings\-as\-errors\fP=false
	Treat warnings received from the server as errors and exit with a non\-zero exit code


.SH EXAMPLE
.PP
.RS

.nf
  # Drain node "foo", even if there are pods not managed by a replication controller, replica set, job, daemon set or stateful set on it
  kubectl drain foo \-\-force
  
  # As above, but abort if there are pods not managed by a replication controller, replica set, job, daemon set or stateful set, and use a grace period of 15 minutes
  kubectl drain foo \-\-grace\-period=900

.fi
.RE


.SH SEE ALSO
.PP
\fBkubectl(1)\fP,


.SH HISTORY
.PP
January 2015, Originally compiled by Eric Paris (eparis at redhat dot com) based on the kubernetes source material, but hopefully they have been automatically generated since!
