.nh
.TH KUBERNETES(1) kubernetes User Manuals
Eric Paris
Jan 2015

.SH NAME
.PP
kubectl create configmap \- Create a config map from a local file, directory or literal value


.SH SYNOPSIS
.PP
\fBkubectl create configmap\fP [OPTIONS]


.SH DESCRIPTION
.PP
Create a config map based on a file, directory, or specified literal value.

.PP
A single config map may package one or more key/value pairs.

.PP
When creating a config map based on a file, the key will default to the basename of the file, and the value will default to the file content.  If the basename is an invalid key, you may specify an alternate key.

.PP
When creating a config map based on a directory, each file whose basename is a valid key in the directory will be packaged into the config map.  Any directory entries except regular files are ignored (e.g. subdirectories, symlinks, devices, pipes, etc).


.SH OPTIONS
.PP
\fB\-\-allow\-missing\-template\-keys\fP=true
	If true, ignore any errors in templates when a field or map key is missing in the template. Only applies to golang and jsonpath output formats.

.PP
\fB\-\-append\-hash\fP=false
	Append a hash of the configmap to its name.

.PP
\fB\-\-dry\-run\fP="none"
	Must be "none", "server", or "client". If client strategy, only print the object that would be sent, without sending it. If server strategy, submit server\-side request without persisting the resource.

.PP
\fB\-\-field\-manager\fP="kubectl\-create"
	Name of the manager used to track field ownership.

.PP
\fB\-\-from\-env\-file\fP=[]
	Specify the path to a file to read lines of key=val pairs to create a configmap (i.e. a Docker .env file).

.PP
\fB\-\-from\-file\fP=[]
	Key file can be specified using its file path, in which case file basename will be used as configmap key, or optionally with a key and file path, in which case the given key will be used.  Specifying a directory will iterate each named file in the directory whose basename is a valid configmap key.

.PP
\fB\-\-from\-literal\fP=[]
	Specify a key and literal value to insert in configmap (i.e. mykey=somevalue)

.PP
\fB\-o\fP, \fB\-\-output\fP=""
	Output format. One of: json|yaml|name|go\-template|go\-template\-file|template|templatefile|jsonpath|jsonpath\-as\-json|jsonpath\-file.

.PP
\fB\-\-save\-config\fP=false
	If true, the configuration of current object will be saved in its annotation. Otherwise, the annotation will be unchanged. This flag is useful when you want to perform kubectl apply on this object in the future.

.PP
\fB\-\-show\-managed\-fields\fP=false
	If true, keep the managedFields when printing objects in JSON or YAML format.

.PP
\fB\-\-template\fP=""
	Template string or path to template file to use when \-o=go\-template, \-o=go\-template\-file. The template format is golang templates [http://golang.org/pkg/text/template/#pkg\-overview].

.PP
\fB\-\-validate\fP=true
	If true, use a schema to validate the input before sending it


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-as\fP=""
	Username to impersonate for the operation. User could be a regular user or a service account in a namespace.

.PP
\fB\-\-as\-group\fP=[]
	Group to impersonate for the operation, this flag can be repeated to specify multiple groups.

.PP
\fB\-\-as\-uid\fP=""
	UID to impersonate for the operation.

.PP
\fB\-\-azure\-container\-registry\-config\fP=""
	Path to the file containing Azure container registry configuration information.

.PP
\fB\-\-cache\-dir\fP="/tmp/kubernetes\-cli\-20211216\-7728\-4tsrr/.brew\_home/.kube/cache"
	Default cache directory

.PP
\fB\-\-certificate\-authority\fP=""
	Path to a cert file for the certificate authority

.PP
\fB\-\-client\-certificate\fP=""
	Path to a client certificate file for TLS

.PP
\fB\-\-client\-key\fP=""
	Path to a client key file for TLS

.PP
\fB\-\-cluster\fP=""
	The name of the kubeconfig cluster to use

.PP
\fB\-\-context\fP=""
	The name of the kubeconfig context to use

.PP
\fB\-\-insecure\-skip\-tls\-verify\fP=false
	If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure

.PP
\fB\-\-kubeconfig\fP=""
	Path to the kubeconfig file to use for CLI requests.

.PP
\fB\-\-match\-server\-version\fP=false
	Require server version to match client version

.PP
\fB\-n\fP, \fB\-\-namespace\fP=""
	If present, the namespace scope for this CLI request

.PP
\fB\-\-password\fP=""
	Password for basic authentication to the API server

.PP
\fB\-\-profile\fP="none"
	Name of profile to capture. One of (none|cpu|heap|goroutine|threadcreate|block|mutex)

.PP
\fB\-\-profile\-output\fP="profile.pprof"
	Name of the file to write the profile to

.PP
\fB\-\-request\-timeout\fP="0"
	The length of time to wait before giving up on a single server request. Non\-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests.

.PP
\fB\-s\fP, \fB\-\-server\fP=""
	The address and port of the Kubernetes API server

.PP
\fB\-\-tls\-server\-name\fP=""
	Server name to use for server certificate validation. If it is not provided, the hostname used to contact the server is used

.PP
\fB\-\-token\fP=""
	Bearer token for authentication to the API server

.PP
\fB\-\-user\fP=""
	The name of the kubeconfig user to use

.PP
\fB\-\-username\fP=""
	Username for basic authentication to the API server

.PP
\fB\-\-version\fP=false
	Print version information and quit

.PP
\fB\-\-warnings\-as\-errors\fP=false
	Treat warnings received from the server as errors and exit with a non\-zero exit code


.SH EXAMPLE
.PP
.RS

.nf
  # Create a new config map named my\-config based on folder bar
  kubectl create configmap my\-config \-\-from\-file=path/to/bar
  
  # Create a new config map named my\-config with specified keys instead of file basenames on disk
  kubectl create configmap my\-config \-\-from\-file=key1=/path/to/bar/file1.txt \-\-from\-file=key2=/path/to/bar/file2.txt
  
  # Create a new config map named my\-config with key1=config1 and key2=config2
  kubectl create configmap my\-config \-\-from\-literal=key1=config1 \-\-from\-literal=key2=config2
  
  # Create a new config map named my\-config from the key=value pairs in the file
  kubectl create configmap my\-config \-\-from\-file=path/to/bar
  
  # Create a new config map named my\-config from an env file
  kubectl create configmap my\-config \-\-from\-env\-file=path/to/foo.env \-\-from\-env\-file=path/to/bar.env

.fi
.RE


.SH SEE ALSO
.PP
\fBkubectl\-create(1)\fP,


.SH HISTORY
.PP
January 2015, Originally compiled by Eric Paris (eparis at redhat dot com) based on the kubernetes source material, but hopefully they have been automatically generated since!
